### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by GregorioFornetti** [explosion5/Dolphins#3]
I would like to have access to the download links for the DOLPHINS dataset. 
What should I do to get it?
Thanks in advance !

**Comment by Merealtea** [comment]
So where is the download link? Thx in advance

**Comment by GregorioFornetti** [comment]
I sent an email to mrq20@mails.tsinghua.edu.cn and they answered me with the links. I dont know if I can share here.

**Comment by Merealtea** [comment]
I see, that's a very&nbsp; helpful suggestion! Thanks!



---Original---
From: "Gregório Fornetti ***@***.***&gt;
Date: Wed, Dec 25, 2024 21:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [explosion5/Dolphins] Dataset download (Issue #3)




 
I sent an email to ***@***.*** and they answered me with the links. I dont know if I can share here.
